### ISSUE TITLE
InventoryClickEvent error with auto Pagination

### ISSUE THREAD

**Issue by gluebaby** [SamJakob/SpiGUI#6] opened 2021-02-27 08:03 UTC
```
Could not pass event InventoryClickEvent to CombatData v1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2277) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at com.samjakob.spigui.SGMenu.nextPage(SGMenu.java:443) ~[?:?]
        at com.samjakob.spigui.SpiGUI.lambda$null$2(SpiGUI.java:94) ~[?:?]
        at com.samjakob.spigui.menu.SGMenuListener.onInventoryClick(SGMenuListener.java:64) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        ... 18 more
```

This error occurs when moving pages with auto-pagination. Weird because the buttons actually work, and cycle pages properly and the inventory setup also is fine.

I also had a quick performance question: 

Right now I'm creating a new SGMenu for every player whenever I need one. I feel as though this could cause performance issues, so I'm curious as to whether or not after the inventory is closed the menu is removed from memory. If I'm just creating a bunch of instances over and over I'd rather just store each SGMenu in a map so I only need one instance for player and can update it as I go.

**Comment by SamJakob** [comment] 2021-03-02 12:32
I'll look into the error now.

Regarding your performance question:
That should be fine as if you don't use the old reference to the inventory after it's closed (i.e. if it's not saved anywhere in a list/map or something), it should be automatically removed from memory by Java's Garbage Collection.

I don't necessarily think it's worth keeping an instance in a map for every player unless it's one inventory per player and they're going to be accessing the inventory a lot because that will prevent the inventories from being collected by GC so you'd be forcing them to stay in memory.

**Comment by SamJakob** [comment] 2021-03-02 12:57
I can't seem to reproduce the issue could you share the following:
- how many pages your GUI has
- your server version (e.g. Bukkit/Spigot version, Minecraft version)
- if possible, some code that produces the error

**Comment by SamJakob** [comment] 2022-02-05 14:50
Closing as this should have been partially resolved by a previous and completely resolved by the latest commit (at time of writing).

**Closed by SamJakob** 2022-02-05 14:50 UTC
Labels: bug, help wanted
